name: Deploy to GCP
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: |
        gcloud auth configure-docker
        docker build -t gcr.io/your-project/reguchat .
        docker push gcr.io/your-project/reguchat
        gcloud run deploy reguchat \
          --image gcr.io/your-project/reguchat \
          --region us-central1 \
          --allow-unauthenticated